language: python

python:
- 3.6
- 3.5
- 3.4
- 2.7 

services:
- redis-server

before_install:
  - pip install coveralls

install:
- pip install -r requirements.txt -r test_requirements.txt

script: py.test tests

after_success:
  - coveralls
